### PR TITLE
use docker/run.sh from rhasspy image

### PR DESCRIPTION
**Pull request by pheelee**
use docker/run.sh from rhasspy image and adapt hass.io options to new name schema

### CODE REVIEW

**Comment by itsme9** [comment]
hi, tried to run your pull and get as having the issue in #205 and get:

usage: Rhasspy [-h] --profile PROFILE [--host HOST] [--port PORT]
               [--system-profiles SYSTEM_PROFILES]
               [--user-profiles USER_PROFILES] [--set SET SET] [--ssl SSL SSL]
               [--log-level LOG_LEVEL]
Rhasspy: error: the following arguments are required: --profile/-p

Home Assistant 0.108.6
HassOS 3.13
Raspberry pi 3b+
arch | armv7l
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.114-v7l
python_version | 3.7.7
version | 0.108.6

Thanks

**Comment by pheelee** [comment]
The docker image https://hub.docker.com/r/synesthesiam/rhasspy-server has to be pushed after merge of https://github.com/synesthesiam/rhasspy/pull/207 to get the addon working again

**Comment by itsme9** [comment]
Sorry didn't know that. Thanks for the reply

**Comment by synesthesiam** [comment]
Thank you, @pheelee

**Pull request merged**
